- name: create db user
  hosts: vm 
  become: true
  become_user: postgres
  vars_files: /etc/ansible/vault.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: connect to postgres
      command: psql

    - name: create db user and add to role
      postgresql_user:
        name: mpopov_test
        password: rywCo3
        state: present


