services:
  node-exporter:
    image: bitnami/node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - monitoring

  grafana:
    image: bitnami/postgres-exporter
    restart: always
    ports:
      - "9187:9187"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
