scrape_configs:
  - job_name: 'postgres_exporter'
    scrape_interval: 120s
    scrape_timeout: 60s
    static_configs:
      - targets:
        - 10.255.254.48:9187
        - 172.24.21.53:9187

  - job_name: 'node_exporter'
    scrape_interval: 120s
    scrape_timeout: 60s
    static_configs:
      - targets:
        - 10.255.254.48:9100
        - 172.24.21.53:9100
        - 10.255.254.101:9100

