---
- name: Deploy monitoring stack
  hosts: all
  become: yes
  vars:
    docker_dir: /home/vagrant/docker

  tasks:
    - name: Ensure Docker directory exists
      file:
        path: "{{ docker_dir }}"
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: "{{ docker_dir }}/docker-compose.yml"
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Create temp directory
      file:
        path: /tmp/monitoring_configs
        state: directory
        
    - name: Copy Prometheus config
      copy:
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
            - job_name: 'node_exporter'
              static_configs:
                - targets: ['node_exporter:9100']
        dest: /tmp/monitoring_configs/prometheus.yml
        
    - name: Copy Grafana provisioning
      copy:
        src: ../grafana/ 
        dest: /tmp/monitoring_configs/grafana/


    - name: Start containers with Docker Compose
      command: docker-compose -f "{{ docker_dir }}/docker-compose.yml" up -d
      args:
        chdir: "{{ docker_dir }}"
      register: compose_up
      changed_when: "'Creating' in compose_up.stdout or 'Starting' in compose_up.stdout"
