version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=qQ345zpHxn#
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch
    restart: always

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch_dashboards
    environment:
      - OPENSEARCH_HOSTS=https://10.255.254.101:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=qQ345zpHxn#
    ports:
      - "5601:5601"
    networks:
      - opensearch
    restart: always
    depends_on:
      - opensearch

  filebeat:
    image: elastic/filebeat:7.12.1
    container_name: filebeat
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      - strict.perms=false
    command: ["-c", "/usr/share/filebeat/filebeat.yml"]
    networks:
      - opensearch
    restart: always
    depends_on:
      - logstash

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    environment:
      - LOGSTASH_JAVA_OPTS="-Xms512m -Xmx512m"
    ports:
      - "5044:5044"
    volumes:
      - /etc/logstash/pipeline:/usr/share/logstash/pipeline
      - /etc/logstash/config:/usr/share/logstash/config
    networks:
      - opensearch
    restart: always
    depends_on:
      - opensearch

networks:
  opensearch:
    driver: bridge